# Generated by Django 5.0.3 on 2024-04-02 21:35

import django.core.validators
import mmablog.models.BlogPostModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='topic_image_small',
            field=models.ImageField(blank=True, null=True, upload_to=mmablog.models.BlogPostModel.topic_image_small_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
