# Generated by Django 5.0.3 on 2024-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0002_blogpost_topic_image_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='topic_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogsubpost',
            name='topic_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
