# Generated by Django 5.0.3 on 2024-04-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0003_blogpost_topic_slug_blogsubpost_topic_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='topic_slug',
            new_name='slug',
        ),
    ]
