# Generated by Django 5.0.3 on 2024-04-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0004_rename_topic_slug_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsubpost',
            old_name='topic_slug',
            new_name='slug',
        ),
    ]
