# Generated by Django 5.0.3 on 2024-04-03 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0005_rename_topic_slug_blogsubpost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogsubpost',
            options={'ordering': ['-topic_image']},
        ),
        migrations.CreateModel(
            name='BlogViewCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('ip_information', models.JSONField(blank=True, null=True)),
                ('viewed_date', models.DateTimeField(auto_now_add=True)),
                ('blogheadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmablog.blogpost')),
            ],
        ),
    ]
