# Generated by Django 5.0.3 on 2024-04-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0006_alter_blogsubpost_options_blogviewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='website',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='subjet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
