# Generated by Django 5.0.3 on 2024-04-03 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0007_remove_blogcomment_website_blogcomment_subjet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='subjet',
            new_name='subject',
        ),
    ]
