# Generated by Django 5.0.3 on 2024-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0008_rename_subjet_blogcomment_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='subject',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
