# Generated by Django 5.0.3 on 2024-04-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0009_remove_blogcomment_subject_blogcomment_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontact',
            name='subject',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
