# Generated by Django 5.0.3 on 2024-04-04 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmablog', '0010_blogcontact_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['name'], name='mmablog_blo_name_c845a3_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['name', 'message', 'comment_date'], name='mmablog_blo_name_8342ae_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['topic_image', 'topic', 'article', 'posted_date'], name='mmablog_blo_topic_i_970a12_idx'),
        ),
        migrations.AddIndex(
            model_name='blogsubpost',
            index=models.Index(fields=['topic_image', 'topic', 'article', 'posted_date'], name='mmablog_blo_topic_i_9f9e56_idx'),
        ),
    ]
